services:
  - type: web
    plan: starter
    previewPlan: starter
    name: rowing-data-scraper-api
    runtime: node
    buildCommand: yarn install && yarn db:generate && yarn build
    preDeployCommand: npx prisma migrate deploy
    startCommand: yarn start
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rowing-database
          property: connectionString
      - key: PORT
        value: 3000
      # Add any other environment variables your scraper might need
      # - fromGroup: rowing-env

databases:
  - name: rowing-database
    databaseName: rowing_database
    user: rowing_database_user
    plan: starter
